
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.11.0.3
//   Input filename:  schema.bond
//   Output filename: schema_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace examples.serialization
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.11.0.3")]
    public partial class Struct
    {
        [global::Bond.Id(0)]
        public uint n { get; set; }

        [global::Bond.Id(1)]
        public string str { get; set; }

        [global::Bond.Id(2)]
        public List<double> items { get; set; }

        public Struct()
            : this("examples.serialization.Struct", "Struct")
        {}

        protected Struct(string fullName, string name)
        {
            str = "";
            items = new List<double>();
        }
    }
} // examples.serialization
