version: '3'
services:
  convert.toint32:
    build: .
    environment:
      - TARGET_FUNCTION=Convert.ToInt32
      - TARGET_PREFIXES=System.Convert,System.ParseNumbers
  datetime.tryparse:
    build: .
    environment:
      - TARGET_FUNCTION=DateTime.TryParse
      - TARGET_PREFIXES=System.DateTime,System.Globalization.DateTime
  decimal.multiply:
    build: .
    environment:
      - TARGET_FUNCTION=Decimal.Multiply
      - TARGET_PREFIXES=System.Decimal,System.Number
  double.tryparse:
    build: .
    environment:
      - TARGET_FUNCTION=Double.TryParse
      - TARGET_PREFIXES=System.Number
  guid.tryparse:
    build: .
    environment:
      - TARGET_FUNCTION=Guid.TryParse
      - TARGET_PREFIXES=System.Guid
  timespan.tryparse:
    build: .
    environment:
      - TARGET_FUNCTION=TimeSpan.TryParse
      - TARGET_PREFIXES=System.TimeSpan,System.Globalization.TimeSpan
  unicodeencoding.getstring:
    build: .
    environment:
      - TARGET_FUNCTION=UnicodeEncoding.GetString
      - TARGET_PREFIXES=System.Text
  utf8encoding.getstring:
    build: .
    environment:
      - TARGET_FUNCTION=UTF8Encoding.GetString
      - TARGET_PREFIXES=System.Text
